version: '2.2'
services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - "POSTGRES_USER=ega"
      - "POSTGRES_PASSWORD=12345"
      - "POSTGRES_DB=postgres"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - default
networks:
  default:
    driver: bridge
volumes:
  postgresdata:
    driver: local


